//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginBehaviac.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginBehaviac.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primitive action 的本地化字符串。
        /// </summary>
        internal static string ActionDesc {
            get {
                return ResourceManager.GetString("ActionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap alwaysFailure_ico {
            get {
                object obj = ResourceManager.GetObject("alwaysFailure_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap alwaysSuccess_ico {
            get {
                object obj = ResourceManager.GetObject("alwaysSuccess_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 AlwaysTransition 的本地化字符串。
        /// </summary>
        internal static string AlwaysTransition {
            get {
                return ResourceManager.GetString("AlwaysTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always Transition 的本地化字符串。
        /// </summary>
        internal static string AlwaysTransitionDesc {
            get {
                return ResourceManager.GetString("AlwaysTransitionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 true if all children are true 的本地化字符串。
        /// </summary>
        internal static string AndDesc {
            get {
                return ResourceManager.GetString("AndDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And and Or are only valid for bool! 的本地化字符串。
        /// </summary>
        internal static string AndOrOnlyValidForBool {
            get {
                return ResourceManager.GetString("AndOrOnlyValidForBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assignment 的本地化字符串。
        /// </summary>
        internal static string Assignment {
            get {
                return ResourceManager.GetString("Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 assign the right to the left 的本地化字符串。
        /// </summary>
        internal static string AssignmentDesc {
            get {
                return ResourceManager.GetString("AssignmentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute 的本地化字符串。
        /// </summary>
        internal static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute 的本地化字符串。
        /// </summary>
        internal static string AttributeDesc {
            get {
                return ResourceManager.GetString("AttributeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domain 的本地化字符串。
        /// </summary>
        internal static string BehaviorDomain {
            get {
                return ResourceManager.GetString("BehaviorDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tag to indicate the type, purpose, etc. 的本地化字符串。
        /// </summary>
        internal static string BehaviorDomainDesc {
            get {
                return ResourceManager.GetString("BehaviorDomainDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blocked 的本地化字符串。
        /// </summary>
        internal static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the impulse blocks the execution and waits for all the events 的本地化字符串。
        /// </summary>
        internal static string BlockedDesc {
            get {
                return ResourceManager.GetString("BlockedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Branch 的本地化字符串。
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Branch 的本地化字符串。
        /// </summary>
        internal static string BranchDesc {
            get {
                return ResourceManager.GetString("BranchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preconditions 的本地化字符串。
        /// </summary>
        internal static string BranchPreconditions {
            get {
                return ResourceManager.GetString("BranchPreconditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tasks 的本地化字符串。
        /// </summary>
        internal static string BranchTasks {
            get {
                return ResourceManager.GetString("BranchTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cast 的本地化字符串。
        /// </summary>
        internal static string CastRight {
            get {
                return ResourceManager.GetString("CastRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the right operand is cast to the left type 的本地化字符串。
        /// </summary>
        internal static string CastRightDesc {
            get {
                return ResourceManager.GetString("CastRightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChildFinishPolicy 的本地化字符串。
        /// </summary>
        internal static string ChildFinishPolicy {
            get {
                return ResourceManager.GetString("ChildFinishPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 how to continue if a child node finishes. 的本地化字符串。
        /// </summary>
        internal static string ChildFinishPolicyDesc {
            get {
                return ResourceManager.GetString("ChildFinishPolicyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CompareGetter 的本地化字符串。
        /// </summary>
        internal static string CompareGetter {
            get {
                return ResourceManager.GetString("CompareGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 call a getter and compare its return value to the right operand 的本地化字符串。
        /// </summary>
        internal static string CompareGetterDesc {
            get {
                return ResourceManager.GetString("CompareGetterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compute 的本地化字符串。
        /// </summary>
        internal static string Compute {
            get {
                return ResourceManager.GetString("Compute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap compute_ico {
            get {
                object obj = ResourceManager.GetObject("compute_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Compute the result of Operand1 and Operand2 and assign it to the Left Operand 的本地化字符串。
        /// </summary>
        internal static string ComputeDesc {
            get {
                return ResourceManager.GetString("ComputeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition 的本地化字符串。
        /// </summary>
        internal static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 condition is usually represented by the agent&apos;s properties, pars, etc. 的本地化字符串。
        /// </summary>
        internal static string ConditionDesc {
            get {
                return ResourceManager.GetString("ConditionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConditionGetter 的本地化字符串。
        /// </summary>
        internal static string ConditionGetter {
            get {
                return ResourceManager.GetString("ConditionGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 call a getter function and compare the return value to the right operand 的本地化字符串。
        /// </summary>
        internal static string ConditionGetterDesc {
            get {
                return ResourceManager.GetString("ConditionGetterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found the customized method : Please firstly integrate the generated source files of the customized method of the agent into your game project. Then export it as meta info into the editor, reload the current workspace. At last, export the behaviors. 的本地化字符串。
        /// </summary>
        internal static string CustomizedMethodError {
            get {
                return ResourceManager.GetString("CustomizedMethodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AlwaysFailure 的本地化字符串。
        /// </summary>
        internal static string DecoratorAlwaysFailure {
            get {
                return ResourceManager.GetString("DecoratorAlwaysFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 it always returns failure no matter what result the child returns 的本地化字符串。
        /// </summary>
        internal static string DecoratorAlwaysFailureDesc {
            get {
                return ResourceManager.GetString("DecoratorAlwaysFailureDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AlwaysRunning 的本地化字符串。
        /// </summary>
        internal static string DecoratorAlwaysRunning {
            get {
                return ResourceManager.GetString("DecoratorAlwaysRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 it always returns running no matter what result the child returns 的本地化字符串。
        /// </summary>
        internal static string DecoratorAlwaysRunningDesc {
            get {
                return ResourceManager.GetString("DecoratorAlwaysRunningDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AlwaysSuccess 的本地化字符串。
        /// </summary>
        internal static string DecoratorAlwaysSuccess {
            get {
                return ResourceManager.GetString("DecoratorAlwaysSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 it always returns success no matter what result the child returns 的本地化字符串。
        /// </summary>
        internal static string DecoratorAlwaysSuccessDesc {
            get {
                return ResourceManager.GetString("DecoratorAlwaysSuccessDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CountLimit 的本地化字符串。
        /// </summary>
        internal static string DecoratorCountLimit {
            get {
                return ResourceManager.GetString("DecoratorCountLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 limit the count of the exucution 的本地化字符串。
        /// </summary>
        internal static string DecoratorCountLimitDesc {
            get {
                return ResourceManager.GetString("DecoratorCountLimitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay 的本地化字符串。
        /// </summary>
        internal static string DecoratorDelay {
            get {
                return ResourceManager.GetString("DecoratorDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay 的本地化字符串。
        /// </summary>
        internal static string DecoratorDelayDesc {
            get {
                return ResourceManager.GetString("DecoratorDelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FailureAfter 的本地化字符串。
        /// </summary>
        internal static string DecoratorFailureAfter {
            get {
                return ResourceManager.GetString("DecoratorFailureAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failue After the specified count 的本地化字符串。
        /// </summary>
        internal static string DecoratorFailureAfterDesc {
            get {
                return ResourceManager.GetString("DecoratorFailureAfterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FailureUntil 的本地化字符串。
        /// </summary>
        internal static string DecoratorFailureUntil {
            get {
                return ResourceManager.GetString("DecoratorFailureUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure until the specified count 的本地化字符串。
        /// </summary>
        internal static string DecoratorFailureUntilDesc {
            get {
                return ResourceManager.GetString("DecoratorFailureUntilDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frames 的本地化字符串。
        /// </summary>
        internal static string DecoratorFrames {
            get {
                return ResourceManager.GetString("DecoratorFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This decorator calls its child within the specified Frames. 的本地化字符串。
        /// </summary>
        internal static string DecoratorFramesDesc {
            get {
                return ResourceManager.GetString("DecoratorFramesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try 的本地化字符串。
        /// </summary>
        internal static string DecoratorIterator {
            get {
                return ResourceManager.GetString("DecoratorIterator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 try each element in the specified array 的本地化字符串。
        /// </summary>
        internal static string DecoratorIteratorDesc {
            get {
                return ResourceManager.GetString("DecoratorIteratorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        internal static string DecoratorLog {
            get {
                return ResourceManager.GetString("DecoratorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging 的本地化字符串。
        /// </summary>
        internal static string DecoratorLogDesc {
            get {
                return ResourceManager.GetString("DecoratorLogDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Message 的本地化字符串。
        /// </summary>
        internal static string DecoratorLogMessage {
            get {
                return ResourceManager.GetString("DecoratorLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log message 的本地化字符串。
        /// </summary>
        internal static string DecoratorLogMessageDesc {
            get {
                return ResourceManager.GetString("DecoratorLogMessageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loop 的本地化字符串。
        /// </summary>
        internal static string DecoratorLoop {
            get {
                return ResourceManager.GetString("DecoratorLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count 的本地化字符串。
        /// </summary>
        internal static string DecoratorLoopCount {
            get {
                return ResourceManager.GetString("DecoratorLoopCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Determines how often the child will be called. If the child fails, the loop is aborted and fails. 的本地化字符串。
        /// </summary>
        internal static string DecoratorLoopCountDesc {
            get {
                return ResourceManager.GetString("DecoratorLoopCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This decorator calls its child n times. -1 is for endless. 的本地化字符串。
        /// </summary>
        internal static string DecoratorLoopDesc {
            get {
                return ResourceManager.GetString("DecoratorLoopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoopUntil 的本地化字符串。
        /// </summary>
        internal static string DecoratorLoopUntil {
            get {
                return ResourceManager.GetString("DecoratorLoopUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 loop until the child returns success/failure or loop for the specified count. 的本地化字符串。
        /// </summary>
        internal static string DecoratorLoopUntilDesc {
            get {
                return ResourceManager.GetString("DecoratorLoopUntilDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not 的本地化字符串。
        /// </summary>
        internal static string DecoratorNot {
            get {
                return ResourceManager.GetString("DecoratorNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This decorator inverts the return value of the attached node. If the attached node fails, it will appear as it has succedded and vice versa. 的本地化字符串。
        /// </summary>
        internal static string DecoratorNotDesc {
            get {
                return ResourceManager.GetString("DecoratorNotDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repeat 的本地化字符串。
        /// </summary>
        internal static string DecoratorRepeat {
            get {
                return ResourceManager.GetString("DecoratorRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 repeat the child node for the specified count to return success, 
        ///or return failure until the child node fails. if the child node keeps running, 
        ///it keeps blocked. but, if the &apos;DecorateChildEnds&apos; is false, it is not blocked.
        ///it only returns success or failure and never returns running. 
        /// 的本地化字符串。
        /// </summary>
        internal static string DecoratorRepeatDesc {
            get {
                return ResourceManager.GetString("DecoratorRepeatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SuccessAfter 的本地化字符串。
        /// </summary>
        internal static string DecoratorSuccessAfter {
            get {
                return ResourceManager.GetString("DecoratorSuccessAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success After the specified count 的本地化字符串。
        /// </summary>
        internal static string DecoratorSuccessAfterDesc {
            get {
                return ResourceManager.GetString("DecoratorSuccessAfterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SuccessUntil 的本地化字符串。
        /// </summary>
        internal static string DecoratorSuccessUntil {
            get {
                return ResourceManager.GetString("DecoratorSuccessUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Succeed until the specified count 的本地化字符串。
        /// </summary>
        internal static string DecoratorSuccessUntilDesc {
            get {
                return ResourceManager.GetString("DecoratorSuccessUntilDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string DecoratorTime {
            get {
                return ResourceManager.GetString("DecoratorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This decorator calls its child within the specified time(milliseconds). 的本地化字符串。
        /// </summary>
        internal static string DecoratorTimeDesc {
            get {
                return ResourceManager.GetString("DecoratorTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Until 的本地化字符串。
        /// </summary>
        internal static string DecoratorUntil {
            get {
                return ResourceManager.GetString("DecoratorUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 by default, the decorator loops until the child returns success. if &apos;until&apos; is false, the decorator loops until the child returns failure. 的本地化字符串。
        /// </summary>
        internal static string DecoratorUntilDesc {
            get {
                return ResourceManager.GetString("DecoratorUntilDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait 的本地化字符串。
        /// </summary>
        internal static string DecoratorWait {
            get {
                return ResourceManager.GetString("DecoratorWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It will wait for a given time to execute the child 的本地化字符串。
        /// </summary>
        internal static string DecoratorWaitDesc {
            get {
                return ResourceManager.GetString("DecoratorWaitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weight 的本地化字符串。
        /// </summary>
        internal static string DecoratorWeight {
            get {
                return ResourceManager.GetString("DecoratorWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weight 的本地化字符串。
        /// </summary>
        internal static string DecoratorWeightDesc {
            get {
                return ResourceManager.GetString("DecoratorWeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Descriptor 的本地化字符串。
        /// </summary>
        internal static string Descriptor {
            get {
                return ResourceManager.GetString("Descriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Descriptor 的本地化字符串。
        /// </summary>
        internal static string DescriptorDesc {
            get {
                return ResourceManager.GetString("DescriptorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Descriptors 的本地化字符串。
        /// </summary>
        internal static string Descriptors {
            get {
                return ResourceManager.GetString("Descriptors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Descriptors 的本地化字符串。
        /// </summary>
        internal static string DescriptorsDesc {
            get {
                return ResourceManager.GetString("DescriptorsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DescriptorWeight 的本地化字符串。
        /// </summary>
        internal static string DescriptorWeightDesc {
            get {
                return ResourceManager.GetString("DescriptorWeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DoneWithinFrame 的本地化字符串。
        /// </summary>
        internal static string DoneWithinFrame {
            get {
                return ResourceManager.GetString("DoneWithinFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 if true, the whole Loop will be blocked until the loop is done within a frame 的本地化字符串。
        /// </summary>
        internal static string DoneWithinFrameDesc {
            get {
                return ResourceManager.GetString("DoneWithinFrameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration 的本地化字符串。
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration 的本地化字符串。
        /// </summary>
        internal static string DurationDesc {
            get {
                return ResourceManager.GetString("DurationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PostAction 的本地化字符串。
        /// </summary>
        internal static string Effector {
            get {
                return ResourceManager.GetString("Effector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap effector_icon {
            get {
                object obj = ResourceManager.GetObject("effector_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 it takes effect when the Node ends. 的本地化字符串。
        /// </summary>
        internal static string EffectorDesc {
            get {
                return ResourceManager.GetString("EffectorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effectors 的本地化字符串。
        /// </summary>
        internal static string Effectors {
            get {
                return ResourceManager.GetString("Effectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effectors 的本地化字符串。
        /// </summary>
        internal static string EffectorsDesc {
            get {
                return ResourceManager.GetString("EffectorsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End 的本地化字符串。
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End 的本地化字符串。
        /// </summary>
        internal static string EndDesc {
            get {
                return ResourceManager.GetString("EndDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Outside 的本地化字符串。
        /// </summary>
        internal static string EndOutside {
            get {
                return ResourceManager.GetString("EndOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End all outside trees 的本地化字符串。
        /// </summary>
        internal static string EndOutsideDesc {
            get {
                return ResourceManager.GetString("EndOutsideDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Status 的本地化字符串。
        /// </summary>
        internal static string EndStatus {
            get {
                return ResourceManager.GetString("EndStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Status 的本地化字符串。
        /// </summary>
        internal static string EndStatusDesc {
            get {
                return ResourceManager.GetString("EndStatusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndTransition 的本地化字符串。
        /// </summary>
        internal static string EndTransition {
            get {
                return ResourceManager.GetString("EndTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndTransition 的本地化字符串。
        /// </summary>
        internal static string EndTransitionDesc {
            get {
                return ResourceManager.GetString("EndTransitionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter 的本地化字符串。
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EnterTo 的本地化字符串。
        /// </summary>
        internal static string EnterTo {
            get {
                return ResourceManager.GetString("EnterTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event 的本地化字符串。
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event 的本地化字符串。
        /// </summary>
        internal static string EventDesc {
            get {
                return ResourceManager.GetString("EventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExitFrom 的本地化字符串。
        /// </summary>
        internal static string ExitFrom {
            get {
                return ResourceManager.GetString("ExitFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExitPolicy 的本地化字符串。
        /// </summary>
        internal static string ExitPolicy {
            get {
                return ResourceManager.GetString("ExitPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExitPolicy, to determine what to do when exiting 的本地化字符串。
        /// </summary>
        internal static string ExitPolicyDesc {
            get {
                return ResourceManager.GetString("ExitPolicyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export File Warning 的本地化字符串。
        /// </summary>
        internal static string ExportFileWarning {
            get {
                return ResourceManager.GetString("ExportFileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FailurePolicy 的本地化字符串。
        /// </summary>
        internal static string FailurePolicy {
            get {
                return ResourceManager.GetString("FailurePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the policy to return FAILURE 的本地化字符串。
        /// </summary>
        internal static string FailurePolicyDesc {
            get {
                return ResourceManager.GetString("FailurePolicyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap failureUntil_ico {
            get {
                object obj = ResourceManager.GetObject("failureUntil_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 False 的本地化字符串。
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 False 的本地化字符串。
        /// </summary>
        internal static string FalseDesc {
            get {
                return ResourceManager.GetString("FalseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frames 的本地化字符串。
        /// </summary>
        internal static string Frames {
            get {
                return ResourceManager.GetString("Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frames 的本地化字符串。
        /// </summary>
        internal static string FramesDesc {
            get {
                return ResourceManager.GetString("FramesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FSM 的本地化字符串。
        /// </summary>
        internal static string FSM {
            get {
                return ResourceManager.GetString("FSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getter 的本地化字符串。
        /// </summary>
        internal static string Getter {
            get {
                return ResourceManager.GetString("Getter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gettter 的本地化字符串。
        /// </summary>
        internal static string GetterDesc {
            get {
                return ResourceManager.GetString("GetterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IfElse 的本地化字符串。
        /// </summary>
        internal static string IfElse {
            get {
                return ResourceManager.GetString("IfElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition 的本地化字符串。
        /// </summary>
        internal static string IfElseCondition {
            get {
                return ResourceManager.GetString("IfElseCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 if condition is true, the &apos;If&apos; is ticked, if condition is false, the &apos;Else&apos; is ticked 的本地化字符串。
        /// </summary>
        internal static string IfElseDesc {
            get {
                return ResourceManager.GetString("IfElseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Else 的本地化字符串。
        /// </summary>
        internal static string IfElseElse {
            get {
                return ResourceManager.GetString("IfElseElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If 的本地化字符串。
        /// </summary>
        internal static string IfElseIf {
            get {
                return ResourceManager.GetString("IfElseIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Impulse 的本地化字符串。
        /// </summary>
        internal static string Impulse {
            get {
                return ResourceManager.GetString("Impulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This node is only visible when one of the associated events were fired. 的本地化字符串。
        /// </summary>
        internal static string ImpulseDesc {
            get {
                return ResourceManager.GetString("ImpulseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Impulse can only be children of Selector 的本地化字符串。
        /// </summary>
        internal static string ImpulseParentError {
            get {
                return ResourceManager.GetString("ImpulseParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no signal specified 的本地化字符串。
        /// </summary>
        internal static string ImpulseWithoutEventError {
            get {
                return ResourceManager.GetString("ImpulseWithoutEventError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsEndState 的本地化字符串。
        /// </summary>
        internal static string IsEndState {
            get {
                return ResourceManager.GetString("IsEndState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 when an &apos;End State&apos; is entered, the FSM is ended. 的本地化字符串。
        /// </summary>
        internal static string IsEndStateDesc {
            get {
                return ResourceManager.GetString("IsEndStateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method 的本地化字符串。
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap method_icon {
            get {
                object obj = ResourceManager.GetObject("method_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Method&apos;s child can only be Branch node 的本地化字符串。
        /// </summary>
        internal static string MethodChildChildError {
            get {
                return ResourceManager.GetString("MethodChildChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Methods can only be Tasks&apos; sub nodes. 的本地化字符串。
        /// </summary>
        internal static string MethodDesc {
            get {
                return ResourceManager.GetString("MethodDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effectors 的本地化字符串。
        /// </summary>
        internal static string MethodEffectors {
            get {
                return ResourceManager.GetString("MethodEffectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method has no children 的本地化字符串。
        /// </summary>
        internal static string MethodNoChildrenError {
            get {
                return ResourceManager.GetString("MethodNoChildrenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method&apos;s parent must be a Task. 的本地化字符串。
        /// </summary>
        internal static string MethodParentError {
            get {
                return ResourceManager.GetString("MethodParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preconditions 的本地化字符串。
        /// </summary>
        internal static string MethodPreconditions {
            get {
                return ResourceManager.GetString("MethodPreconditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tasks 的本地化字符串。
        /// </summary>
        internal static string MethodTasks {
            get {
                return ResourceManager.GetString("MethodTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No action branch is specified 的本地化字符串。
        /// </summary>
        internal static string NoActionError {
            get {
                return ResourceManager.GetString("NoActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no condition specified! 的本地化字符串。
        /// </summary>
        internal static string NoConditionError {
            get {
                return ResourceManager.GetString("NoConditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actions 的本地化字符串。
        /// </summary>
        internal static string NodeGroupActions {
            get {
                return ResourceManager.GetString("NodeGroupActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attachments 的本地化字符串。
        /// </summary>
        internal static string NodeGroupAttachments {
            get {
                return ResourceManager.GetString("NodeGroupAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Branches 的本地化字符串。
        /// </summary>
        internal static string NodeGroupBranches {
            get {
                return ResourceManager.GetString("NodeGroupBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Composites 的本地化字符串。
        /// </summary>
        internal static string NodeGroupComposites {
            get {
                return ResourceManager.GetString("NodeGroupComposites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditions 的本地化字符串。
        /// </summary>
        internal static string NodeGroupConditions {
            get {
                return ResourceManager.GetString("NodeGroupConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decorators 的本地化字符串。
        /// </summary>
        internal static string NodeGroupDecorators {
            get {
                return ResourceManager.GetString("NodeGroupDecorators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Events 的本地化字符串。
        /// </summary>
        internal static string NodeGroupEvents {
            get {
                return ResourceManager.GetString("NodeGroupEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Impulses 的本地化字符串。
        /// </summary>
        internal static string NodeGroupImpulses {
            get {
                return ResourceManager.GetString("NodeGroupImpulses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leaves 的本地化字符串。
        /// </summary>
        internal static string NodeGroupLeaves {
            get {
                return ResourceManager.GetString("NodeGroupLeaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No effector branch is specified 的本地化字符串。
        /// </summary>
        internal static string NoEffectorError {
            get {
                return ResourceManager.GetString("NoEffectorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no child specified 的本地化字符串。
        /// </summary>
        internal static string NoMethosError {
            get {
                return ResourceManager.GetString("NoMethosError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Noop 的本地化字符串。
        /// </summary>
        internal static string Noop {
            get {
                return ResourceManager.GetString("Noop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no operation 的本地化字符串。
        /// </summary>
        internal static string NoopDesc {
            get {
                return ResourceManager.GetString("NoopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task&apos;s param not specified 的本地化字符串。
        /// </summary>
        internal static string NoParam {
            get {
                return ResourceManager.GetString("NoParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Precondition branch is specified 的本地化字符串。
        /// </summary>
        internal static string NoPreconditionError {
            get {
                return ResourceManager.GetString("NoPreconditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No task specified 的本地化字符串。
        /// </summary>
        internal static string NoTask {
            get {
                return ResourceManager.GetString("NoTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operand is not complete! 的本地化字符串。
        /// </summary>
        internal static string OperandError {
            get {
                return ResourceManager.GetString("OperandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operand is not complete! 的本地化字符串。
        /// </summary>
        internal static string OperatandIsNotComplete {
            get {
                return ResourceManager.GetString("OperatandIsNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Or 的本地化字符串。
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 true if any one of the children is true 的本地化字符串。
        /// </summary>
        internal static string OrDesc {
            get {
                return ResourceManager.GetString("OrDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parallel 的本地化字符串。
        /// </summary>
        internal static string Parallel {
            get {
                return ResourceManager.GetString("Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 all the children are updated in parallel 的本地化字符串。
        /// </summary>
        internal static string ParallelDesc {
            get {
                return ResourceManager.GetString("ParallelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PreAction 的本地化字符串。
        /// </summary>
        internal static string PreAction {
            get {
                return ResourceManager.GetString("PreAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 to check a precondition before taking action 的本地化字符串。
        /// </summary>
        internal static string PreActionDesc {
            get {
                return ResourceManager.GetString("PreActionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PreAction 的本地化字符串。
        /// </summary>
        internal static string Precondition {
            get {
                return ResourceManager.GetString("Precondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap precondition_icon {
            get {
                object obj = ResourceManager.GetObject("precondition_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 PreAction is an action or precondition which is executed/evaluated before &apos;entering&apos; a node.  的本地化字符串。
        /// </summary>
        internal static string PreconditionDesc {
            get {
                return ResourceManager.GetString("PreconditionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When 的本地化字符串。
        /// </summary>
        internal static string PreconditionPhase {
            get {
                return ResourceManager.GetString("PreconditionPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 when to evalute the precondition 的本地化字符串。
        /// </summary>
        internal static string PreconditionPhaseDesc {
            get {
                return ResourceManager.GetString("PreconditionPhaseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Predicate 的本地化字符串。
        /// </summary>
        internal static string Predicate {
            get {
                return ResourceManager.GetString("Predicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 compare properties/pars with the right operand 的本地化字符串。
        /// </summary>
        internal static string PredicateDesc {
            get {
                return ResourceManager.GetString("PredicateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proposition 的本地化字符串。
        /// </summary>
        internal static string Proposition {
            get {
                return ResourceManager.GetString("Proposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proposition 的本地化字符串。
        /// </summary>
        internal static string PropositionDesc {
            get {
                return ResourceManager.GetString("PropositionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap query_icon {
            get {
                object obj = ResourceManager.GetObject("query_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 sub trees are queried 的本地化字符串。
        /// </summary>
        internal static string QueryDesc {
            get {
                return ResourceManager.GetString("QueryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RandomGenerator 的本地化字符串。
        /// </summary>
        internal static string RandomGenerator {
            get {
                return ResourceManager.GetString("RandomGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can specify a method to return a float value between 0.0 and 1.0 as the random number. 的本地化字符串。
        /// </summary>
        internal static string RandomGeneratorDesc {
            get {
                return ResourceManager.GetString("RandomGeneratorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RandomGenerator is not specified， the default one is used! 的本地化字符串。
        /// </summary>
        internal static string RandomGeneratorNotSpecified {
            get {
                return ResourceManager.GetString("RandomGeneratorNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference 的本地化字符串。
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference 的本地化字符串。
        /// </summary>
        internal static string ReferenceDesc {
            get {
                return ResourceManager.GetString("ReferenceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reinit 的本地化字符串。
        /// </summary>
        internal static string Reinit {
            get {
                return ResourceManager.GetString("Reinit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap repeat_icon {
            get {
                object obj = ResourceManager.GetObject("repeat_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Requery 的本地化字符串。
        /// </summary>
        internal static string Requery {
            get {
                return ResourceManager.GetString("Requery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Children 的本地化字符串。
        /// </summary>
        internal static string ResetChildren {
            get {
                return ResourceManager.GetString("ResetChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset the running children 的本地化字符串。
        /// </summary>
        internal static string ResetChildrenDesc {
            get {
                return ResourceManager.GetString("ResetChildrenDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selector 的本地化字符串。
        /// </summary>
        internal static string Selector {
            get {
                return ResourceManager.GetString("Selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This node will call its attached nodes in the given order until one succeeds. If all attached nodes fail, this node fails, too. 的本地化字符串。
        /// </summary>
        internal static string SelectorDesc {
            get {
                return ResourceManager.GetString("SelectorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectorMonitor 的本地化字符串。
        /// </summary>
        internal static string SelectorLoop {
            get {
                return ResourceManager.GetString("SelectorLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap selectorLoop_ico {
            get {
                object obj = ResourceManager.GetObject("selectorLoop_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Children are not WithPrecondition 的本地化字符串。
        /// </summary>
        internal static string SelectorLoopChildChildError {
            get {
                return ResourceManager.GetString("SelectorLoopChildChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dynamic Selector, it keep selecting from the children nodes until one succeeds. 的本地化字符串。
        /// </summary>
        internal static string SelectorLoopDesc {
            get {
                return ResourceManager.GetString("SelectorLoopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectorProbability 的本地化字符串。
        /// </summary>
        internal static string SelectorProbability {
            get {
                return ResourceManager.GetString("SelectorProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap selectorProbability_ico {
            get {
                object obj = ResourceManager.GetObject("selectorProbability_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Selector by probability 的本地化字符串。
        /// </summary>
        internal static string SelectorProbabilityDesc {
            get {
                return ResourceManager.GetString("SelectorProbabilityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectorStochastic 的本地化字符串。
        /// </summary>
        internal static string SelectorStochastic {
            get {
                return ResourceManager.GetString("SelectorStochastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap selectorStochastic_ico {
            get {
                object obj = ResourceManager.GetObject("selectorStochastic_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Selector Stochastic 的本地化字符串。
        /// </summary>
        internal static string SelectorStochasticDesc {
            get {
                return ResourceManager.GetString("SelectorStochasticDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence 的本地化字符串。
        /// </summary>
        internal static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This node will call its attached nodes in the given order. If any of the attached nodes fails, this node fails as well. 的本地化字符串。
        /// </summary>
        internal static string SequenceDesc {
            get {
                return ResourceManager.GetString("SequenceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SequenceStochastic 的本地化字符串。
        /// </summary>
        internal static string SequenceStochastic {
            get {
                return ResourceManager.GetString("SequenceStochastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sequenceStochastic_ico {
            get {
                object obj = ResourceManager.GetObject("sequenceStochastic_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence Stochastic 的本地化字符串。
        /// </summary>
        internal static string SequenceStochasticDesc {
            get {
                return ResourceManager.GetString("SequenceStochasticDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string StartCondition {
            get {
                return ResourceManager.GetString("StartCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string StartConditionDesc {
            get {
                return ResourceManager.GetString("StartConditionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap state_icon {
            get {
                object obj = ResourceManager.GetObject("state_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        internal static string StateDesc {
            get {
                return ResourceManager.GetString("StateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StatusTransition 的本地化字符串。
        /// </summary>
        internal static string StatusTransition {
            get {
                return ResourceManager.GetString("StatusTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 for a subtree state, to transition or not based on its returnning status  的本地化字符串。
        /// </summary>
        internal static string StatusTransitionDesc {
            get {
                return ResourceManager.GetString("StatusTransitionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SuccessPolicy 的本地化字符串。
        /// </summary>
        internal static string SuccessPolicy {
            get {
                return ResourceManager.GetString("SuccessPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the policy to return SUCESS 的本地化字符串。
        /// </summary>
        internal static string SuccessPolicyDesc {
            get {
                return ResourceManager.GetString("SuccessPolicyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap successUntil_ico {
            get {
                object obj = ResourceManager.GetObject("successUntil_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Target Id 的本地化字符串。
        /// </summary>
        internal static string TargetId {
            get {
                return ResourceManager.GetString("TargetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Id 的本地化字符串。
        /// </summary>
        internal static string TargetIdDesc {
            get {
                return ResourceManager.GetString("TargetIdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task 的本地化字符串。
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap task_icon {
            get {
                object obj = ResourceManager.GetObject("task_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Children are not Method 的本地化字符串。
        /// </summary>
        internal static string TaskChildChildError {
            get {
                return ResourceManager.GetString("TaskChildChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Task can be expanded into other tasks or actions on the runtime. 的本地化字符串。
        /// </summary>
        internal static string TaskDesc {
            get {
                return ResourceManager.GetString("TaskDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 task has no children. 的本地化字符串。
        /// </summary>
        internal static string TaskNoChildrenError {
            get {
                return ResourceManager.GetString("TaskNoChildrenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task is not specified 的本地化字符串。
        /// </summary>
        internal static string TaskNoMethod {
            get {
                return ResourceManager.GetString("TaskNoMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task 的本地化字符串。
        /// </summary>
        internal static string TaskPrototype {
            get {
                return ResourceManager.GetString("TaskPrototype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task 的本地化字符串。
        /// </summary>
        internal static string TaskPrototypeDesc {
            get {
                return ResourceManager.GetString("TaskPrototypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transition 的本地化字符串。
        /// </summary>
        internal static string Transition {
            get {
                return ResourceManager.GetString("Transition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap transition_icon {
            get {
                object obj = ResourceManager.GetObject("transition_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Transition 的本地化字符串。
        /// </summary>
        internal static string TransitionCondition {
            get {
                return ResourceManager.GetString("TransitionCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transition 的本地化字符串。
        /// </summary>
        internal static string TransitionConditionDesc {
            get {
                return ResourceManager.GetString("TransitionConditionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transition Mode 的本地化字符串。
        /// </summary>
        internal static string TransitionMode {
            get {
                return ResourceManager.GetString("TransitionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 it determines how the transition works: 1. when the condition is true, it transitions. 2. when the method succeeds/fails/ends it transitions. 的本地化字符串。
        /// </summary>
        internal static string TransitionModeDesc {
            get {
                return ResourceManager.GetString("TransitionModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 transition can only link from a state to another state. 的本地化字符串。
        /// </summary>
        internal static string TransitionParentError {
            get {
                return ResourceManager.GetString("TransitionParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TransitionPhase 的本地化字符串。
        /// </summary>
        internal static string TransitionPhase {
            get {
                return ResourceManager.GetString("TransitionPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 in which case to transition 的本地化字符串。
        /// </summary>
        internal static string TransitionPhaseDesc {
            get {
                return ResourceManager.GetString("TransitionPhaseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 True 的本地化字符串。
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 True 的本地化字符串。
        /// </summary>
        internal static string TrueDesc {
            get {
                return ResourceManager.GetString("TrueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap try_icon {
            get {
                object obj = ResourceManager.GetObject("try_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait 的本地化字符串。
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait for the specified miliseconds 的本地化字符串。
        /// </summary>
        internal static string WaitDesc {
            get {
                return ResourceManager.GetString("WaitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WaitforSignal 的本地化字符串。
        /// </summary>
        internal static string WaitforSignal {
            get {
                return ResourceManager.GetString("WaitforSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap waitforSignal_ico {
            get {
                object obj = ResourceManager.GetObject("waitforSignal_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 blocked until the predicates are true 的本地化字符串。
        /// </summary>
        internal static string WaitforSignalDesc {
            get {
                return ResourceManager.GetString("WaitforSignalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WaitFrames 的本地化字符串。
        /// </summary>
        internal static string WaitFrames {
            get {
                return ResourceManager.GetString("WaitFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait for the specified frames 的本地化字符串。
        /// </summary>
        internal static string WaitFramesDesc {
            get {
                return ResourceManager.GetString("WaitFramesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WaitFramesState 的本地化字符串。
        /// </summary>
        internal static string WaitFramesState {
            get {
                return ResourceManager.GetString("WaitFramesState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WaitFramesState 的本地化字符串。
        /// </summary>
        internal static string WaitFramesStateDesc {
            get {
                return ResourceManager.GetString("WaitFramesStateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WaitState 的本地化字符串。
        /// </summary>
        internal static string WaitState {
            get {
                return ResourceManager.GetString("WaitState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WaitState 的本地化字符串。
        /// </summary>
        internal static string WaitStateDesc {
            get {
                return ResourceManager.GetString("WaitStateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WaitTransition 的本地化字符串。
        /// </summary>
        internal static string WaitTransition {
            get {
                return ResourceManager.GetString("WaitTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WaitTransition can only be appended to WaitState or WaitFramesState 的本地化字符串。
        /// </summary>
        internal static string WaitTransitionDesc {
            get {
                return ResourceManager.GetString("WaitTransitionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weight 的本地化字符串。
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weight 的本地化字符串。
        /// </summary>
        internal static string WeightDesc {
            get {
                return ResourceManager.GetString("WeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Its parent node is not SelectorProbability. 的本地化字符串。
        /// </summary>
        internal static string WeightParentError {
            get {
                return ResourceManager.GetString("WeightParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WithPrecondition 的本地化字符串。
        /// </summary>
        internal static string WithPrecondition {
            get {
                return ResourceManager.GetString("WithPrecondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        internal static string WithPreconditionAction {
            get {
                return ResourceManager.GetString("WithPreconditionAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 it has two branches:precondition and action. action branch can only be called if the precondition branch returns success. 的本地化字符串。
        /// </summary>
        internal static string WithPreconditionDesc {
            get {
                return ResourceManager.GetString("WithPreconditionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WithPrecondition can only be inserted to SelectorLoop. 的本地化字符串。
        /// </summary>
        internal static string WithPreconditionParentError {
            get {
                return ResourceManager.GetString("WithPreconditionParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Precondition 的本地化字符串。
        /// </summary>
        internal static string WithPreconditionPrecondition {
            get {
                return ResourceManager.GetString("WithPreconditionPrecondition", resourceCulture);
            }
        }
    }
}
