// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

public class SecondAgent : behaviac.Agent
///<<< BEGIN WRITING YOUR CODE SecondAgent
///<<< END WRITING YOUR CODE
{
	private ISecondAgentImp _methodImp;
	public SecondAgent(ISecondAgentImp methodImp,behaviac.Workspace workspace):base(workspace)
	{
	    _methodImp=methodImp;
	}
	private int p2 = 0;
	public void _set_p2(int value)
	{
		p2 = value;
	}
	public int _get_p2()
	{
		return p2;
	}

///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE

}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

