//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Behaviac.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Behaviac.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Actions 的本地化字符串。
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Enter Breakpoint 的本地化字符串。
        /// </summary>
        internal static string AddEnterBreakpoint {
            get {
                return ResourceManager.GetString("AddEnterBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Exit Breakpoint 的本地化字符串。
        /// </summary>
        internal static string AddExitBreakpoint {
            get {
                return ResourceManager.GetString("AddExitBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Planning Breakpoint 的本地化字符串。
        /// </summary>
        internal static string AddPlanningBreakpoint {
            get {
                return ResourceManager.GetString("AddPlanningBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter 的本地化字符串。
        /// </summary>
        internal static string AgentEnter {
            get {
                return ResourceManager.GetString("AgentEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter 的本地化字符串。
        /// </summary>
        internal static string AgentEnterDesc {
            get {
                return ResourceManager.GetString("AgentEnterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event 的本地化字符串。
        /// </summary>
        internal static string AgentEvent {
            get {
                return ResourceManager.GetString("AgentEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 event 的本地化字符串。
        /// </summary>
        internal static string AgentEventDesc {
            get {
                return ResourceManager.GetString("AgentEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string AgentExit {
            get {
                return ResourceManager.GetString("AgentExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string AgentExitDesc {
            get {
                return ResourceManager.GetString("AgentExitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method 的本地化字符串。
        /// </summary>
        internal static string AgentMethod {
            get {
                return ResourceManager.GetString("AgentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 What to do when this node is updating. It can not be empty. 的本地化字符串。
        /// </summary>
        internal static string AgentMethodDesc {
            get {
                return ResourceManager.GetString("AgentMethodDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If the agent type is changed, the properties and methods in the leaf nodes may be reset. Are you sure change it? 的本地化字符串。
        /// </summary>
        internal static string AgentTypeChangedWarning {
            get {
                return ResourceManager.GetString("AgentTypeChangedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agent Types are not compatible! 的本地化字符串。
        /// </summary>
        internal static string AgentTypeError {
            get {
                return ResourceManager.GetString("AgentTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attach 的本地化字符串。
        /// </summary>
        internal static string AttachBasic {
            get {
                return ResourceManager.GetString("AttachBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attachment 的本地化字符串。
        /// </summary>
        internal static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attachment Id 的本地化字符串。
        /// </summary>
        internal static string AttachmentId {
            get {
                return ResourceManager.GetString("AttachmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attachment Id 的本地化字符串。
        /// </summary>
        internal static string AttachmentIdDesc {
            get {
                return ResourceManager.GetString("AttachmentIdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attachments 的本地化字符串。
        /// </summary>
        internal static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All meta files will be merged, and the previous mete files will be removed. Are you sure? 的本地化字符串。
        /// </summary>
        internal static string AutoMergeMetaFilesInfo {
            get {
                return ResourceManager.GetString("AutoMergeMetaFilesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behavior 的本地化字符串。
        /// </summary>
        internal static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agent Type 的本地化字符串。
        /// </summary>
        internal static string BehaviorAgentType {
            get {
                return ResourceManager.GetString("BehaviorAgentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the agent type controlling the behavior 的本地化字符串。
        /// </summary>
        internal static string BehaviorAgentTypeDesc {
            get {
                return ResourceManager.GetString("BehaviorAgentTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This node represents the current behavior. 的本地化字符串。
        /// </summary>
        internal static string BehaviorDesc {
            get {
                return ResourceManager.GetString("BehaviorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domain 的本地化字符串。
        /// </summary>
        internal static string BehaviorDomain {
            get {
                return ResourceManager.GetString("BehaviorDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 a tag(like, attack, defence, etc.) 的本地化字符串。
        /// </summary>
        internal static string BehaviorDomainDesc {
            get {
                return ResourceManager.GetString("BehaviorDomainDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domains 的本地化字符串。
        /// </summary>
        internal static string BehaviorDomains {
            get {
                return ResourceManager.GetString("BehaviorDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tags(like attack, defence, etc.) speparated by space 的本地化字符串。
        /// </summary>
        internal static string BehaviorDomainsDesc {
            get {
                return ResourceManager.GetString("BehaviorDomainsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EventName 的本地化字符串。
        /// </summary>
        internal static string BehaviorEventName {
            get {
                return ResourceManager.GetString("BehaviorEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EventName 的本地化字符串。
        /// </summary>
        internal static string BehaviorEventNameDesc {
            get {
                return ResourceManager.GetString("BehaviorEventNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filename 的本地化字符串。
        /// </summary>
        internal static string BehaviorFilename {
            get {
                return ResourceManager.GetString("BehaviorFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file which holds this behaviour. 的本地化字符串。
        /// </summary>
        internal static string BehaviorFilenameDesc {
            get {
                return ResourceManager.GetString("BehaviorFilenameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behavior is empty. 的本地化字符串。
        /// </summary>
        internal static string BehaviorIsEmptyError {
            get {
                return ResourceManager.GetString("BehaviorIsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Association 的本地化字符串。
        /// </summary>
        internal static string BinaryOperator {
            get {
                return ResourceManager.GetString("BinaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How to connect multiple conditions 的本地化字符串。
        /// </summary>
        internal static string BinaryOperatorDesc {
            get {
                return ResourceManager.GetString("BinaryOperatorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic 的本地化字符串。
        /// </summary>
        internal static string CategoryBasic {
            get {
                return ResourceManager.GetString("CategoryBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment 的本地化字符串。
        /// </summary>
        internal static string CategoryComment {
            get {
                return ResourceManager.GetString("CategoryComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Design 的本地化字符串。
        /// </summary>
        internal static string CategoryDesign {
            get {
                return ResourceManager.GetString("CategoryDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Par 的本地化字符串。
        /// </summary>
        internal static string CategoryPar {
            get {
                return ResourceManager.GetString("CategoryPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        internal static string CategoryVersion {
            get {
                return ResourceManager.GetString("CategoryVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Composites 的本地化字符串。
        /// </summary>
        internal static string Composites {
            get {
                return ResourceManager.GetString("Composites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 False 的本地化字符串。
        /// </summary>
        internal static string ConditionConnectorsFalse {
            get {
                return ResourceManager.GetString("ConditionConnectorsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 True 的本地化字符串。
        /// </summary>
        internal static string ConditionConnectorsTrue {
            get {
                return ResourceManager.GetString("ConditionConnectorsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not 的本地化字符串。
        /// </summary>
        internal static string ConditionNegate {
            get {
                return ResourceManager.GetString("ConditionNegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not 的本地化字符串。
        /// </summary>
        internal static string ConditionNegateDesc {
            get {
                return ResourceManager.GetString("ConditionNegateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditions 的本地化字符串。
        /// </summary>
        internal static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect Error 的本地化字符串。
        /// </summary>
        internal static string ConnectError {
            get {
                return ResourceManager.GetString("ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Const 的本地化字符串。
        /// </summary>
        internal static string Const {
            get {
                return ResourceManager.GetString("Const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found the customized agent : Please firstly integrate the generated source files of the customized agent into your game project. Then export it as meta info into the editor, reload the current workspace. At last, export the behaviors. 的本地化字符串。
        /// </summary>
        internal static string CustomizedAgentError {
            get {
                return ResourceManager.GetString("CustomizedAgentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found the customized method : Please firstly integrate the generated source files of the customized method of the agent into your game project. Then export it as meta info into the editor, reload the current workspace. At last, export the behaviors. 的本地化字符串。
        /// </summary>
        internal static string CustomizedMethodError {
            get {
                return ResourceManager.GetString("CustomizedMethodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DecorateChildEnds 的本地化字符串。
        /// </summary>
        internal static string DecorateWhenChildEnds {
            get {
                return ResourceManager.GetString("DecorateWhenChildEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 if true, then the decorator only decorates the child when the child ends(success/failure) 的本地化字符串。
        /// </summary>
        internal static string DecorateWhenChildEndsDesc {
            get {
                return ResourceManager.GetString("DecorateWhenChildEndsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decorator has no child. 的本地化字符串。
        /// </summary>
        internal static string DecoratorHasNoChildError {
            get {
                return ResourceManager.GetString("DecoratorHasNoChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decorators 的本地化字符串。
        /// </summary>
        internal static string Decorators {
            get {
                return ResourceManager.GetString("Decorators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description :  的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Descriptor 的本地化字符串。
        /// </summary>
        internal static string DescriptorDesc {
            get {
                return ResourceManager.GetString("DescriptorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DescriptorRef 的本地化字符串。
        /// </summary>
        internal static string DescriptorRefDesc {
            get {
                return ResourceManager.GetString("DescriptorRefDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;None&gt; 的本地化字符串。
        /// </summary>
        internal static string DesignerNodePropertyNone {
            get {
                return ResourceManager.GetString("DesignerNodePropertyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Enter Breakpoint 的本地化字符串。
        /// </summary>
        internal static string DisableEnterBreakpoint {
            get {
                return ResourceManager.GetString("DisableEnterBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Exit Breakpoint 的本地化字符串。
        /// </summary>
        internal static string DisableExitBreakpoint {
            get {
                return ResourceManager.GetString("DisableExitBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Planning Breakpoint 的本地化字符串。
        /// </summary>
        internal static string DisablePlanningBreakpoint {
            get {
                return ResourceManager.GetString("DisablePlanningBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effector 的本地化字符串。
        /// </summary>
        internal static string Effector {
            get {
                return ResourceManager.GetString("Effector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 it takes effect when the node succeeds. 的本地化字符串。
        /// </summary>
        internal static string EffectorDesc {
            get {
                return ResourceManager.GetString("EffectorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When 的本地化字符串。
        /// </summary>
        internal static string EffectorPhase {
            get {
                return ResourceManager.GetString("EffectorPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 this determines when it takes effect, when successful or failed? 的本地化字符串。
        /// </summary>
        internal static string EffectorPhaseDesc {
            get {
                return ResourceManager.GetString("EffectorPhaseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter 的本地化字符串。
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Action 的本地化字符串。
        /// </summary>
        internal static string EnterAction {
            get {
                return ResourceManager.GetString("EnterAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 What to do when this node is entered. It can be empty. 的本地化字符串。
        /// </summary>
        internal static string EnterActionDesc {
            get {
                return ResourceManager.GetString("EnterActionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event 的本地化字符串。
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block Event 的本地化字符串。
        /// </summary>
        internal static string EventBlockEvent {
            get {
                return ResourceManager.GetString("EventBlockEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If true the event is blocked. 的本地化字符串。
        /// </summary>
        internal static string EventBlockEventDesc {
            get {
                return ResourceManager.GetString("EventBlockEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event 的本地化字符串。
        /// </summary>
        internal static string EventDesc {
            get {
                return ResourceManager.GetString("EventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EventHandling 的本地化字符串。
        /// </summary>
        internal static string EventHandling {
            get {
                return ResourceManager.GetString("EventHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event 的本地化字符串。
        /// </summary>
        internal static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The event name registered by REGISTER_EVENT on c++ side 的本地化字符串。
        /// </summary>
        internal static string EventNameDesc {
            get {
                return ResourceManager.GetString("EventNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The additional assembly {0} could not be loaded. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdditionalAssemblyNotLoaded {
            get {
                return ResourceManager.GetString("ExceptionAdditionalAssemblyNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The used behaviour node type does not implement Nodes.Behavior or is abstract. 的本地化字符串。
        /// </summary>
        internal static string ExceptionBehaviorNodeTypeInvalid {
            get {
                return ResourceManager.GetString("ExceptionBehaviorNodeTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both styles may not be null. 的本地化字符串。
        /// </summary>
        internal static string ExceptionBothStylesNull {
            get {
                return ResourceManager.GetString("ExceptionBothStylesNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is not allowed to create a node view data from another one. Use the original node for this. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCreateNodeViewDataFromNodeViewData {
            get {
                return ResourceManager.GetString("ExceptionCreateNodeViewDataFromNodeViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default style may not be null. 的本地化字符串。
        /// </summary>
        internal static string ExceptionDefaultStyleNull {
            get {
                return ResourceManager.GetString("ExceptionDefaultStyleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not retrieve the node of {0}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionDesignerAttributeCouldNotRetrieveNode {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeCouldNotRetrieveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not parse value {0} 的本地化字符串。
        /// </summary>
        internal static string ExceptionDesignerAttributeEnumCouldNotParseValue {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeEnumCouldNotParseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not read value {0} 的本地化字符串。
        /// </summary>
        internal static string ExceptionDesignerAttributeEnumCouldNotReadValue {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeEnumCouldNotReadValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid enum index found {0} 的本地化字符串。
        /// </summary>
        internal static string ExceptionDesignerAttributeEnumIllegalEnumIndex {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeEnumIllegalEnumIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enum value {0} is illegal 的本地化字符串。
        /// </summary>
        internal static string ExceptionDesignerAttributeEnumValueIllegal {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeEnumValueIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enum expected {0} 的本地化字符串。
        /// </summary>
        internal static string ExceptionDesignerAttributeExpectedEnum {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeExpectedEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illegal boolean value {0} 的本地化字符串。
        /// </summary>
        internal static string ExceptionDesignerAttributeIllegalBooleanValue {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeIllegalBooleanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illegal float value {0} 的本地化字符串。
        /// </summary>
        internal static string ExceptionDesignerAttributeIllegalFloatValue {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeIllegalFloatValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illegal integer value {0} 的本地化字符串。
        /// </summary>
        internal static string ExceptionDesignerAttributeIllegalIntegerValue {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeIllegalIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid type 的本地化字符串。
        /// </summary>
        internal static string ExceptionDesignerAttributeInvalidType {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given type is not allowed by this property. 的本地化字符串。
        /// </summary>
        internal static string ExceptionDesignerAttributeUnsupportedType {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A duplicated connector identifier was found. The identifier must be unique over the whole solution! 的本地化字符串。
        /// </summary>
        internal static string ExceptionDuplicatedConnectorIdentifier {
            get {
                return ResourceManager.GetString("ExceptionDuplicatedConnectorIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing attribute &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string ExceptionFileManagerXMLMissingAttribute {
            get {
                return ResourceManager.GetString("ExceptionFileManagerXMLMissingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name of a definition may not contain any spaces. 的本地化字符串。
        /// </summary>
        internal static string ExceptionInvalidDefinitionName {
            get {
                return ResourceManager.GetString("ExceptionInvalidDefinitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation is only allowed on NodeViewData nodes. 的本地化字符串。
        /// </summary>
        internal static string ExceptionIsNotNodeViewData {
            get {
                return ResourceManager.GetString("ExceptionIsNotNodeViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The linked property {0} could not be found in {1}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionLinkedPropertyNotFound {
            get {
                return ResourceManager.GetString("ExceptionLinkedPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not create event of type {0}. Constructor may only require the node it is created for as a parameter. 的本地化字符串。
        /// </summary>
        internal static string ExceptionMissingEventConstructor {
            get {
                return ResourceManager.GetString("ExceptionMissingEventConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not create node of type {0}. Constructor may not require any parameters. 的本地化字符串。
        /// </summary>
        internal static string ExceptionMissingNodeConstructor {
            get {
                return ResourceManager.GetString("ExceptionMissingNodeConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not create override of type {0}. Constructor may only require the node it is created for as a parameter. 的本地化字符串。
        /// </summary>
        internal static string ExceptionMissingOverrideConstructor {
            get {
                return ResourceManager.GetString("ExceptionMissingOverrideConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There can only be one BehaviorManagerInterface. 的本地化字符串。
        /// </summary>
        internal static string ExceptionMultipleBehaviorManagerInterfaces {
            get {
                return ResourceManager.GetString("ExceptionMultipleBehaviorManagerInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only one loadable or savable attribute is allowed. 的本地化字符串。
        /// </summary>
        internal static string ExceptionMultipleDesignerAttributes {
            get {
                return ResourceManager.GetString("ExceptionMultipleDesignerAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The node is not allowed to have more children. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNodeHasTooManyChildren {
            get {
                return ResourceManager.GetString("ExceptionNodeHasTooManyChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node is not a child of this node. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNodeIsNoChild {
            get {
                return ResourceManager.GetString("ExceptionNodeIsNoChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No subitem for the connector could be found. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNoSubItemForConnector {
            get {
                return ResourceManager.GetString("ExceptionNoSubItemForConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given type does not implement the DefaultObject interface. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNotImplementDefaultObject {
            get {
                return ResourceManager.GetString("ExceptionNotImplementDefaultObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All designer properties must be readable. 的本地化字符串。
        /// </summary>
        internal static string ExceptionPropertyCannotBeRead {
            get {
                return ResourceManager.GetString("ExceptionPropertyCannotBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All designer properties must be writable or flagged as read only and no save. 的本地化字符串。
        /// </summary>
        internal static string ExceptionPropertyCannotBeWritten {
            get {
                return ResourceManager.GetString("ExceptionPropertyCannotBeWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The used referenced behaviour node type does not implement Nodes.ReferencedBehavior or is abstract. 的本地化字符串。
        /// </summary>
        internal static string ExceptionReferencedBehaviorNodeTypeInvalid {
            get {
                return ResourceManager.GetString("ExceptionReferencedBehaviorNodeTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The subitem does not belong to this node. 的本地化字符串。
        /// </summary>
        internal static string ExceptionSubItemIsNoChild {
            get {
                return ResourceManager.GetString("ExceptionSubItemIsNoChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given color is not handled. 的本地化字符串。
        /// </summary>
        internal static string ExceptionUnhandledCommentColor {
            get {
                return ResourceManager.GetString("ExceptionUnhandledCommentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhandled node shape. 的本地化字符串。
        /// </summary>
        internal static string ExceptionUnhandledNodeShape {
            get {
                return ResourceManager.GetString("ExceptionUnhandledNodeShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No such event type {0}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionUnknownEventType {
            get {
                return ResourceManager.GetString("ExceptionUnknownEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No such node type {0}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionUnknownNodeType {
            get {
                return ResourceManager.GetString("ExceptionUnknownNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given node tag type cannot be used with the given type. 的本地化字符串。
        /// </summary>
        internal static string ExceptionWrongNodeTagType {
            get {
                return ResourceManager.GetString("ExceptionWrongNodeTagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit Action 的本地化字符串。
        /// </summary>
        internal static string ExitAction {
            get {
                return ResourceManager.GetString("ExitAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 What to do when this node is exited. It can be empty. behaviac::GetNodeExitStatus() can be used to query the exit status. 的本地化字符串。
        /// </summary>
        internal static string ExitActionDesc {
            get {
                return ResourceManager.GetString("ExitActionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export File Warning 的本地化字符串。
        /// </summary>
        internal static string ExportFileWarning {
            get {
                return ResourceManager.GetString("ExportFileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please install the latest designer to open the behaviors. 的本地化字符串。
        /// </summary>
        internal static string FileVersionWarning {
            get {
                return ResourceManager.GetString("FileVersionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Warning 的本地化字符串。
        /// </summary>
        internal static string FileWarning {
            get {
                return ResourceManager.GetString("FileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FSM 的本地化字符串。
        /// </summary>
        internal static string FSM {
            get {
                return ResourceManager.GetString("FSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTN 的本地化字符串。
        /// </summary>
        internal static string HTN {
            get {
                return ResourceManager.GetString("HTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay 的本地化字符串。
        /// </summary>
        internal static string ImpulseDelay {
            get {
                return ResourceManager.GetString("ImpulseDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The time which must have passed before the node can become active again. 的本地化字符串。
        /// </summary>
        internal static string ImpulseDelayDesc {
            get {
                return ResourceManager.GetString("ImpulseDelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration 的本地化字符串。
        /// </summary>
        internal static string ImpulseDuration {
            get {
                return ResourceManager.GetString("ImpulseDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Determines how old the oldest event may be for this node to become valid. 的本地化字符串。
        /// </summary>
        internal static string ImpulseDurationDesc {
            get {
                return ResourceManager.GetString("ImpulseDurationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InterruptIf 的本地化字符串。
        /// </summary>
        internal static string InterruptIf {
            get {
                return ResourceManager.GetString("InterruptIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The meta file is invalid 的本地化字符串。
        /// </summary>
        internal static string InvalidMeta {
            get {
                return ResourceManager.GetString("InvalidMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The meta file is invalid : {0}
        ///Please reexport the meta with the latest runtime! 的本地化字符串。
        /// </summary>
        internal static string InvalidMetaInfo {
            get {
                return ResourceManager.GetString("InvalidMetaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leaf 的本地化字符串。
        /// </summary>
        internal static string Leaf {
            get {
                return ResourceManager.GetString("Leaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load configure data file {0} failed:
        ///
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string LoadConfigureError {
            get {
                return ResourceManager.GetString("LoadConfigureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load debug data file {0} failed:
        ///
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string LoadDebugDataError {
            get {
                return ResourceManager.GetString("LoadDebugDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Error 的本地化字符串。
        /// </summary>
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Warning 的本地化字符串。
        /// </summary>
        internal static string LoadWarning {
            get {
                return ResourceManager.GetString("LoadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load the workspace file {0}! 的本地化字符串。
        /// </summary>
        internal static string LoadWorkspaceError {
            get {
                return ResourceManager.GetString("LoadWorkspaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method 的本地化字符串。
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The methods &quot;{0}&quot; and &quot;{1}&quot; have the same display name &quot;{2}&quot;. Please modify their display name, and then export them as the meta info. 的本地化字符串。
        /// </summary>
        internal static string MethodWithSameDisplayName {
            get {
                return ResourceManager.GetString("MethodWithSameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode 的本地化字符串。
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode 的本地化字符串。
        /// </summary>
        internal static string ModeDesc {
            get {
                return ResourceManager.GetString("ModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string NameDesc {
            get {
                return ResourceManager.GetString("NameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Agent 的本地化字符串。
        /// </summary>
        internal static string NoAgent {
            get {
                return ResourceManager.GetString("NoAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node 的本地化字符串。
        /// </summary>
        internal static string NodeBasic {
            get {
                return ResourceManager.GetString("NodeBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class Version 的本地化字符串。
        /// </summary>
        internal static string NodeClassVersion {
            get {
                return ResourceManager.GetString("NodeClassVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The version of the class. Node is updated when version is lower than class version. 的本地化字符串。
        /// </summary>
        internal static string NodeClassVersionDesc {
            get {
                return ResourceManager.GetString("NodeClassVersionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background 的本地化字符串。
        /// </summary>
        internal static string NodeCommentBackground {
            get {
                return ResourceManager.GetString("NodeCommentBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The background color rendered behind the node and its children. 的本地化字符串。
        /// </summary>
        internal static string NodeCommentBackgroundDesc {
            get {
                return ResourceManager.GetString("NodeCommentBackgroundDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string NodeCommentText {
            get {
                return ResourceManager.GetString("NodeCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The comment shown for the node and its children. 的本地化字符串。
        /// </summary>
        internal static string NodeCommentTextDesc {
            get {
                return ResourceManager.GetString("NodeCommentTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string NodeVersion {
            get {
                return ResourceManager.GetString("NodeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The version of the node. Used to update nodes when the structure changes. 的本地化字符串。
        /// </summary>
        internal static string NodeVersionDesc {
            get {
                return ResourceManager.GetString("NodeVersionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No method 的本地化字符串。
        /// </summary>
        internal static string NoMethod {
            get {
                return ResourceManager.GetString("NoMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameters are not completed. 的本地化字符串。
        /// </summary>
        internal static string NoParam {
            get {
                return ResourceManager.GetString("NoParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResultOption is Invalid and ResultFunctor is not set. 的本地化字符串。
        /// </summary>
        internal static string NoResultFunctor {
            get {
                return ResourceManager.GetString("NoResultFunctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        internal static string OperandLeft {
            get {
                return ResourceManager.GetString("OperandLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Operand 的本地化字符串。
        /// </summary>
        internal static string OperandLeftDesc {
            get {
                return ResourceManager.GetString("OperandLeftDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        internal static string OperandRight {
            get {
                return ResourceManager.GetString("OperandRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Operand 的本地化字符串。
        /// </summary>
        internal static string OperandRightDesc {
            get {
                return ResourceManager.GetString("OperandRightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator 的本地化字符串。
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator 的本地化字符串。
        /// </summary>
        internal static string OperatorDesc {
            get {
                return ResourceManager.GetString("OperatorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator Type 的本地化字符串。
        /// </summary>
        internal static string OperatorType {
            get {
                return ResourceManager.GetString("OperatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        internal static string OperatorType_And {
            get {
                return ResourceManager.GetString("OperatorType_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assignment 的本地化字符串。
        /// </summary>
        internal static string OperatorType_Assignment {
            get {
                return ResourceManager.GetString("OperatorType_Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equal 的本地化字符串。
        /// </summary>
        internal static string OperatorType_Equal {
            get {
                return ResourceManager.GetString("OperatorType_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Greater 的本地化字符串。
        /// </summary>
        internal static string OperatorType_Greater {
            get {
                return ResourceManager.GetString("OperatorType_Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GreaterEqual 的本地化字符串。
        /// </summary>
        internal static string OperatorType_GreaterEqual {
            get {
                return ResourceManager.GetString("OperatorType_GreaterEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iterator 的本地化字符串。
        /// </summary>
        internal static string OperatorType_In {
            get {
                return ResourceManager.GetString("OperatorType_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Less 的本地化字符串。
        /// </summary>
        internal static string OperatorType_Less {
            get {
                return ResourceManager.GetString("OperatorType_Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LessEqual 的本地化字符串。
        /// </summary>
        internal static string OperatorType_LessEqual {
            get {
                return ResourceManager.GetString("OperatorType_LessEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non Equal 的本地化字符串。
        /// </summary>
        internal static string OperatorType_NonEqual {
            get {
                return ResourceManager.GetString("OperatorType_NonEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Or 的本地化字符串。
        /// </summary>
        internal static string OperatorType_Or {
            get {
                return ResourceManager.GetString("OperatorType_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator Type Selection 的本地化字符串。
        /// </summary>
        internal static string OperatorTypeDesc {
            get {
                return ResourceManager.GetString("OperatorTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Override 的本地化字符串。
        /// </summary>
        internal static string OverrideProperty {
            get {
                return ResourceManager.GetString("OverrideProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A property of the node attached to which will be overridden. 的本地化字符串。
        /// </summary>
        internal static string OverridePropertyDesc {
            get {
                return ResourceManager.GetString("OverridePropertyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random 的本地化字符串。
        /// </summary>
        internal static string OverrideRandom {
            get {
                return ResourceManager.GetString("OverrideRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes an attribute to return a random value. 的本地化字符串。
        /// </summary>
        internal static string OverrideRandomDesc {
            get {
                return ResourceManager.GetString("OverrideRandomDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Par 的本地化字符串。
        /// </summary>
        internal static string Par {
            get {
                return ResourceManager.GetString("Par", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parallel has no children. 的本地化字符串。
        /// </summary>
        internal static string ParallelNoChildrenError {
            get {
                return ResourceManager.GetString("ParallelNoChildrenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parallel has only one child and could be removed. 的本地化字符串。
        /// </summary>
        internal static string ParallelOnlyOneChildError {
            get {
                return ResourceManager.GetString("ParallelOnlyOneChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User defined par 的本地化字符串。
        /// </summary>
        internal static string ParInfo {
            get {
                return ResourceManager.GetString("ParInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Par:&apos;{0}&apos; is defined but not used. 的本地化字符串。
        /// </summary>
        internal static string ParWarningInfo {
            get {
                return ResourceManager.GetString("ParWarningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Precondition 的本地化字符串。
        /// </summary>
        internal static string Precondition {
            get {
                return ResourceManager.GetString("Precondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PreconditionFailResult 的本地化字符串。
        /// </summary>
        internal static string PreconditionFailResult {
            get {
                return ResourceManager.GetString("PreconditionFailResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action status if the precondition is false 的本地化字符串。
        /// </summary>
        internal static string PreconditionFailResultDesc {
            get {
                return ResourceManager.GetString("PreconditionFailResultDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prefab 的本地化字符串。
        /// </summary>
        internal static string Prefab {
            get {
                return ResourceManager.GetString("Prefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prefab Dirty 的本地化字符串。
        /// </summary>
        internal static string PrefabDirty {
            get {
                return ResourceManager.GetString("PrefabDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prefab Name 的本地化字符串。
        /// </summary>
        internal static string PrefabName {
            get {
                return ResourceManager.GetString("PrefabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prefab Node Id 的本地化字符串。
        /// </summary>
        internal static string PrefabNodeId {
            get {
                return ResourceManager.GetString("PrefabNodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click F1 to check its document. 的本地化字符串。
        /// </summary>
        internal static string PressF1 {
            get {
                return ResourceManager.GetString("PressF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties of {0} 的本地化字符串。
        /// </summary>
        internal static string PropertiesOf {
            get {
                return ResourceManager.GetString("PropertiesOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prototype :  的本地化字符串。
        /// </summary>
        internal static string Prototype {
            get {
                return ResourceManager.GetString("Prototype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max 的本地化字符串。
        /// </summary>
        internal static string RandomMax {
            get {
                return ResourceManager.GetString("RandomMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The highest possible value. 的本地化字符串。
        /// </summary>
        internal static string RandomMaxDesc {
            get {
                return ResourceManager.GetString("RandomMaxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min 的本地化字符串。
        /// </summary>
        internal static string RandomMin {
            get {
                return ResourceManager.GetString("RandomMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The lowest possible value. 的本地化字符串。
        /// </summary>
        internal static string RandomMinDesc {
            get {
                return ResourceManager.GetString("RandomMinDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SubTree 的本地化字符串。
        /// </summary>
        internal static string ReferencedBehavior {
            get {
                return ResourceManager.GetString("ReferencedBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found circular reference. 的本地化字符串。
        /// </summary>
        internal static string ReferencedBehaviorCircularReferenceError {
            get {
                return ResourceManager.GetString("ReferencedBehaviorCircularReferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This node works like an action which calls the subtree. 的本地化字符串。
        /// </summary>
        internal static string ReferencedBehaviorDesc {
            get {
                return ResourceManager.GetString("ReferencedBehaviorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The referenced behavior file &quot;{0}&quot; does not exist! 的本地化字符串。
        /// </summary>
        internal static string ReferencedBehaviorError {
            get {
                return ResourceManager.GetString("ReferencedBehaviorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behavior Filename 的本地化字符串。
        /// </summary>
        internal static string ReferencedBehaviorFilename {
            get {
                return ResourceManager.GetString("ReferencedBehaviorFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReferencedBehaviorPath 的本地化字符串。
        /// </summary>
        internal static string ReferencedBehaviorPath {
            get {
                return ResourceManager.GetString("ReferencedBehaviorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SubTree RelativePath 的本地化字符串。
        /// </summary>
        internal static string ReferencedBehaviorPathDesc {
            get {
                return ResourceManager.GetString("ReferencedBehaviorPathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need to specify the Referencd Tree or provide a method to return it. 的本地化字符串。
        /// </summary>
        internal static string ReferencedTreeOrMethodNeeded {
            get {
                return ResourceManager.GetString("ReferencedTreeOrMethodNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Referenced behavior has errors! 的本地化字符串。
        /// </summary>
        internal static string ReferenceError {
            get {
                return ResourceManager.GetString("ReferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A method returning a string as the referenced behavior&apos;s path 的本地化字符串。
        /// </summary>
        internal static string ReferenceGenerator {
            get {
                return ResourceManager.GetString("ReferenceGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A method returning a string as the referenced behavior&apos;s path 的本地化字符串。
        /// </summary>
        internal static string ReferenceGeneratorDesc {
            get {
                return ResourceManager.GetString("ReferenceGeneratorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Referenced behavior has warnings! 的本地化字符串。
        /// </summary>
        internal static string ReferenceWarning {
            get {
                return ResourceManager.GetString("ReferenceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Enter Breakpoint 的本地化字符串。
        /// </summary>
        internal static string RemoveEnterBreakpoint {
            get {
                return ResourceManager.GetString("RemoveEnterBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Exit Breakpoint 的本地化字符串。
        /// </summary>
        internal static string RemoveExitBreakpoint {
            get {
                return ResourceManager.GetString("RemoveExitBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Planning Breakpoint 的本地化字符串。
        /// </summary>
        internal static string RemovePlanningBreakpoint {
            get {
                return ResourceManager.GetString("RemovePlanningBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Error 的本地化字符串。
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save file {0} failed:
        ///
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string SaveFileError {
            get {
                return ResourceManager.GetString("SaveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save File Warning 的本地化字符串。
        /// </summary>
        internal static string SaveFileWarning {
            get {
                return ResourceManager.GetString("SaveFileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} file is read only.
        ///
        ///Yes     : Overwrite it.
        ///No      : Don&apos;t overwrite it.
        ///Cancel : Abort all. 的本地化字符串。
        /// </summary>
        internal static string SaveWarningInfo {
            get {
                return ResourceManager.GetString("SaveWarningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save the workspace file {0}! 的本地化字符串。
        /// </summary>
        internal static string SaveWorkspaceError {
            get {
                return ResourceManager.GetString("SaveWorkspaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selector has no children. 的本地化字符串。
        /// </summary>
        internal static string SelectorNoChildrenError {
            get {
                return ResourceManager.GetString("SelectorNoChildrenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selector has only one child and could be removed. 的本地化字符串。
        /// </summary>
        internal static string SelectorOnlyOneChildError {
            get {
                return ResourceManager.GetString("SelectorOnlyOneChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selectors 的本地化字符串。
        /// </summary>
        internal static string Selectors {
            get {
                return ResourceManager.GetString("Selectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence has no children. 的本地化字符串。
        /// </summary>
        internal static string SequenceNoChildrenError {
            get {
                return ResourceManager.GetString("SequenceNoChildrenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence has only one child and could be removed. 的本地化字符串。
        /// </summary>
        internal static string SequenceOnlyOneChildError {
            get {
                return ResourceManager.GetString("SequenceOnlyOneChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequences 的本地化字符串。
        /// </summary>
        internal static string Sequences {
            get {
                return ResourceManager.GetString("Sequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Signal 的本地化字符串。
        /// </summary>
        internal static string Signal {
            get {
                return ResourceManager.GetString("Signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status Functor 的本地化字符串。
        /// </summary>
        internal static string StatusFunctor {
            get {
                return ResourceManager.GetString("StatusFunctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a method, and use its return value as the Status of updating the Action. StatusFunctor is a Functor returning EBTStatus with the Method&apos;s return value as the only parameter or without any parameter when the Method returns void. 的本地化字符串。
        /// </summary>
        internal static string StatusFunctorDesc {
            get {
                return ResourceManager.GetString("StatusFunctorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status Option 的本地化字符串。
        /// </summary>
        internal static string StatusOption {
            get {
                return ResourceManager.GetString("StatusOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are 3 cases to determine the Action&apos;s status(Success/Failure/Running) after a tick:
        ///1. if the Method returns &apos;EBTStatus&apos;, then it is used as this Action&apos;s status, the StatusOption and StatusFunction is disabled.
        ///2. otherwise the StatusOption is enabled and when others except Invalid is selected, it will be used as the Status directly, StatusFunctor is disabled.
        ///3. when Invalid is selected, StatusFunctor is enabled, it uses the StatusFunctor to return a EBTStatus.  的本地化字符串。
        /// </summary>
        internal static string StatusOptionDesc {
            get {
                return ResourceManager.GetString("StatusOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task 的本地化字符串。
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task can only accept methods or only one child. 的本地化字符串。
        /// </summary>
        internal static string TaskMethodChildrenOrOne {
            get {
                return ResourceManager.GetString("TaskMethodChildrenOrOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task has no children 的本地化字符串。
        /// </summary>
        internal static string TaskNoMethod {
            get {
                return ResourceManager.GetString("TaskNoMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transition 的本地化字符串。
        /// </summary>
        internal static string Transition {
            get {
                return ResourceManager.GetString("Transition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigged Once 的本地化字符串。
        /// </summary>
        internal static string TriggeredOnce {
            get {
                return ResourceManager.GetString("TriggeredOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigged Once, Stop Checking once triggered 的本地化字符串。
        /// </summary>
        internal static string TriggeredOnceDesc {
            get {
                return ResourceManager.GetString("TriggeredOnceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger Mode 的本地化字符串。
        /// </summary>
        internal static string TriggerMode {
            get {
                return ResourceManager.GetString("TriggerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        internal static string TriggerMode_Return {
            get {
                return ResourceManager.GetString("TriggerMode_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When the child ends, it gives control back and the interupted node continues to execute. 的本地化字符串。
        /// </summary>
        internal static string TriggerMode_ReturnDesc {
            get {
                return ResourceManager.GetString("TriggerMode_ReturnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer 的本地化字符串。
        /// </summary>
        internal static string TriggerMode_Transfer {
            get {
                return ResourceManager.GetString("TriggerMode_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The original tree is aborted and reset. It gives control to the new tree. 的本地化字符串。
        /// </summary>
        internal static string TriggerMode_TransferDesc {
            get {
                return ResourceManager.GetString("TriggerMode_TransferDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It determine how the triggered bt gives control back when it ends. 的本地化字符串。
        /// </summary>
        internal static string TriggerModeDesc {
            get {
                return ResourceManager.GetString("TriggerModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The referenced behavior &quot;{0}&quot; has been modified latterly not in the current behavior &quot;{1}&quot;, so the undo/redo operation would get the undesired result.
        ///Are your sure continue the undo/redo operation? 的本地化字符串。
        /// </summary>
        internal static string UndoWarningInfo {
            get {
                return ResourceManager.GetString("UndoWarningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sec 的本地化字符串。
        /// </summary>
        internal static string UnitsSeconds {
            get {
                return ResourceManager.GetString("UnitsSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResultFunctor has wrong result type, i.e. not EBTStatus type, or its parameter is not the same as the result of the action method. 的本地化字符串。
        /// </summary>
        internal static string WrongResultFunctor {
            get {
                return ResourceManager.GetString("WrongResultFunctor", resourceCulture);
            }
        }
    }
}
